# Generated by Django 4.2.17 on 2025-12-26 16:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(choices=[('ticketed', 'Ticketed Venue'), ('public', 'Public Spots'), ('mixed', 'Mixed')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('contact_email', models.EmailField(max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Number of credits available')),
                ('total_purchased', models.IntegerField(default=0, help_text='Total credits ever purchased')),
                ('total_spent', models.IntegerField(default=0, help_text='Total credits ever spent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_description', models.CharField(blank=True, max_length=500)),
                ('access_type', models.CharField(choices=[('free_ticketed', 'Free (Ticketed Venue)'), ('free_public', 'Free (Public)'), ('paid', 'Paid (Credits Required)')], max_length=20)),
                ('credit_cost', models.IntegerField(default=1, help_text='Number of credits required to access this spot')),
                ('qr_code_data', models.CharField(max_length=500, unique=True)),
                ('nfc_tag_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_spent', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('spot_access', 'Spot Access'), ('refund', 'Refund')], default='spot_access', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('info_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.infospot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_purchased', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('text_content', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_content/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'aac', 'm4a'])])),
                ('audio_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tenants.infospot')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Content Editor')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='SpotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('content_language', models.CharField(max_length=10)),
                ('audio_played', models.BooleanField(default=False)),
                ('audio_play_duration', models.IntegerField(blank=True, help_text='Seconds of audio played', null=True)),
                ('text_viewed', models.BooleanField(default=False)),
                ('info_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.infospot')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous ticketed venue access', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['info_spot', 'accessed_at'], name='tenants_spo_info_sp_3fd545_idx'), models.Index(fields=['user', 'accessed_at'], name='tenants_spo_user_id_ea847c_idx'), models.Index(fields=['session_id'], name='tenants_spo_session_85cc5b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='infospot',
            index=models.Index(fields=['tenant', 'is_active'], name='tenants_inf_tenant__53d569_idx'),
        ),
        migrations.AddIndex(
            model_name='infospot',
            index=models.Index(fields=['uuid'], name='tenants_inf_uuid_7f146c_idx'),
        ),
        migrations.AddIndex(
            model_name='infospot',
            index=models.Index(fields=['qr_code_data'], name='tenants_inf_qr_code_b048b5_idx'),
        ),
        migrations.AddIndex(
            model_name='infospot',
            index=models.Index(fields=['nfc_tag_id'], name='tenants_inf_nfc_tag_deaef5_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', 'created_at'], name='tenants_cre_user_id_932467_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='tenants_cre_tenant__4ea798_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['info_spot', 'user'], name='tenants_cre_info_sp_0454dd_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['user', 'created_at'], name='tenants_cre_user_id_2bee81_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['stripe_payment_intent_id'], name='tenants_cre_stripe__50efef_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['status', 'created_at'], name='tenants_cre_status_388c5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('info_spot', 'language')},
        ),
    ]
