# Generated by Django 4.2.17 on 2025-12-31 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantadmin',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tenantadmin',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['user', 'created_at'], name='tenants_cre_user_id_2bee81_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['stripe_payment_intent_id'], name='tenants_cre_stripe__50efef_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpurchase',
            index=models.Index(fields=['status', 'created_at'], name='tenants_cre_status_388c5b_idx'),
        ),
    ]
