# Generated by Django 5.2.10 on 2026-01-18 13:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('motto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Motto')),
                ('logo', models.FileField(upload_to='logo/', verbose_name='Logo')),
                ('primary_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
